apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: web-env
        - name: PHOENIX_ENDPOINT_SECRET
          valueFrom:
            configMapKeyRef:
              key: PHOENIX_ENDPOINT_SECRET
              name: web-env
        image: web
        name: web
        ports:
        - containerPort: 5000
        resources: 
          limits:
            cpu: "500m"
            memory: "128Mi"
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
      restartPolicy: Always
      imagePullPolicy: Always 
status: {}
